apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector: #selector de que pods gestionara
    matchLabels:
      app: event-bus
  template: #template de cada pod que creara
    metadata:
      labels:
        app: event-bus #agrega una etiqueta para saber que sera gestionado por este depl
    spec:
      containers:
        - name: event-bus
          image: gustavocondezo/event-bus

#Para agregar otro objecto de kubernets con triple guion (sino puede ser otro archivo)
#agregamos un despliegue de tipo servicio
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv # nombre del service, se llamara en las llamdas http
spec:
  selector:
    app: event-bus #Selector de a que pods afectara este service
  type: ClusterIP #Si no se pone sera x defecto ClusterIP
  #ClusterIP PERMITE QUE SE CONECTEN ENTRE PODS
  #NodePort permite que el puerto este disponible fuera
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005 #puerto en el cual la aplicacion (o container) escucha
