apiVersion: apps/v1
kind: Deployment # Tipo creamos un deploymentchi

metadata:
  name: posts-depl #Nombre del deployment
spec: # definir comportamiento del deployment
  replicas: 1
  selector:
    matchLabels: #incdicamos al deployment que estara a cargo de los pods con la metaadata app: posts
      app: posts
  template: # Caracteristicas de los pods a crearse
    metadata: # le añadimos metdata
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: gustavocondezo/posts

---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  type: ClusterIP #Si no se pone sera x defecto ClusterIP
  #ClusterIP PERMITE QUE SE CONECTEN ENTRE PODS
  #NodePort permite que el puerto este disponible fuera
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
